### ISSUE TITLE
[Bug]: Cluster::getExtraFieldWrapperAttributes does not exist.

### ISSUE THREAD

**Issue by schaper1337** [GuavaCZ/filament-clusters#12]
### What happened?

With the Introduction of extra Field Wrappers for Form Components (https://github.com/filamentphp/filament/pull/12782)  in Filament v3.2.80 the Cluster Component cannot be used anymore: 

Method Guava\FilamentClusters\Forms\Cluster::getExtraFieldWrapperAttributes does not exist.

### How to reproduce the bug

Cluster::make([
Select::make('xxx'),
])

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

11

**Comment by StaffCollab** [comment]
This kills my application, please help.
I will revert my composer updates for now, but I need the updates.

**Comment by aleskapot** [comment]
> This kills my application, please help. I will revert my composer updates for now, but I need the updates.

Just extend base `Guava\FilamentClusters\Forms\Cluster` and use trait `Filament\Forms\Components\Concerns\HasExtraFieldWrapperAttributes` in your subclass.

**Comment by lukas-frey** [comment]
Fixed in #11
