### ISSUE TITLE
[Bug]: Button has a white background 

### ISSUE THREAD

**Issue by khanakia** [GuavaCZ/filament-clusters#13]
### What happened?

I want to input Group with the button on the right it's not working

There is also no documentation I could find

![Screenshot 2024-09-11 at 11 27 36 AM](https://github.com/user-attachments/assets/c9fbc470-b5a7-48ea-a54b-fcf7e2ae38f4)

### How to reproduce the bug

```php
Cluster::make([
                Forms\Components\TextInput::make("name")->maxLength(255)->required()
                ,
                Forms\Components\Actions::make([
                    Forms\Components\Actions\Action::make('Generate Slug')
                        ->icon('heroicon-s-bolt')
                        ->label('')
                        ->button()


                ]),
            ]),
```

### Package Version

latest

### PHP Version

8.2.-

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by lukas-frey** [comment]
Why don't you use suffix / prefix actions? And the color you can change using the `color` method on the actions.

**Comment by khanakia** [comment]
Would you happen to have an example? 

I do not want to change the color it is just a Slug Generate Button which will take the name of the post and set the slug into the slug TextInput

**Comment by lukas-frey** [comment]
I'd do something like this: 

```php
Cluster::make([
    Forms\Components\TextInput::make("name")
        ->maxLength(255)
        ->required()
        ->suffixAction(Forms\Components\Actions\Action::make('Generate Slug')
            ->icon('heroicon-s-bolt')
            ->iconButton()
        ),
    ]),
```

https://filamentphp.com/docs/3.x/forms/actions#adding-an-affix-action-to-a-field

**Comment by lukas-frey** [comment]
Actually in your case, if you only want an action next to a text input, you don't need Clusters at all.

**Comment by khanakia** [comment]
Thanks
